appName: 618623-nginx-app

image:
  name: joshmitac/helmapp
  tag: nginx

configmap:
  name: nginx-config
  data:
    WELCOME_ROSA: 'Welcome to NGINX on ROSA!'
    
secret:
  name: nginx-secret
  data:
    APP_KEY: "MySecretKey123"

serviceAccount:
  name: nginx-sa

pvc:
  name: nginx-pvc
  storage: 5Gi

service:
  name: nginx-service
  type: ClusterIP
  port: 80

route:
  name: nginx-route
  host: ""

role:
  name: nginx-role
  roleBinding: nginx-rolebinding